# Generated by Django 2.1.4 on 2019-01-06 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyMoney', '0002_auto_20190104_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='shares',
        ),
        migrations.AddField(
            model_name='share',
            name='expense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='MyMoney.Expense'),
            preserve_default=False,
        ),
    ]
