# Generated by Django 2.1.4 on 2019-02-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMoney', '0005_auto_20190224_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
