# Generated by Django 2.1.4 on 2019-03-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('MyMoney', '0006_auto_20190224_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='share',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
