# Generated by Django 2.1.4 on 2019-03-24 18:23

from django.db import migrations


def migrate_foreign_key(apps, schema_editor):
    """
    Fonction custom pour peupler les GenericForeignKeys introduites par la migration 0008
    """
    Share = apps.get_model('MyMoney', 'Share')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    expense_content_type = ContentType.objects.get(app_label='MyMoney', model='expense')

    for share in Share.objects.all():
        share.content_type = expense_content_type
        share.object_id = share.expense.pk
        share.save()


class Migration(migrations.Migration):

    dependencies = [
        ('MyMoney', '0008_auto_20190324_1822'),
    ]

    operations = [
        migrations.RunPython(migrate_foreign_key)
    ]
