# Generated by Django 2.1.4 on 2019-03-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyMoney', '0009_auto_20190324_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='expense',
        ),
        migrations.AlterField(
            model_name='share',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='share',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
